arduino-libraries/WiFiNINA

- src/utility/spi_drv.cpp
> Add support for MKR Vidor 4000

- src/WiFiClient.cpp
- src/WiFiNINA.h
- src/WiFiUdp.cpp
- src/WiFiUdp.h
- src/utility/WiFiSocketBuffer.cpp
- src/utility/WiFiSocketBuffer.h
- src/utility/wl_definitions.h
This addresses #9.
This pull request adds a socket buffer for received data at the MCU level, so SPI commands to the NINA a reduced. This improves read performance of `WiFiClient` and `WiFiUDP`.
> Add socket buffer

- src/WiFi.cpp
I think this will help with #16 (for non-iOS hotspots).
@ubidefeo could you please try thing change out?
> Don't fail begin if not connected in 5 seconds

- .travis.yml
- examples/CheckFirmwareVersion/CheckFirmwareVersion.ino
- examples/ScanNetworks/ScanNetworks.ino
- examples/ScanNetworksAdvanced/ScanNetworksAdvanced.ino
- examples/SimpleWebServerWiFi/SimpleWebServerWiFi.ino
- examples/WiFiChatServer/WiFiChatServer.ino
- examples/WiFiPing/WiFiPing.ino
- examples/WiFiWebClient/WiFiWebClient.ino
- src/WiFi.h
- Added check firmware version example, CheckFirmwareVersion.ino
- Modified the sketchs documentation , it was alligned with board module name
>  Added new example and documentation examples changes

- examples/AP_SimpleWebServer/AP_SimpleWebServer.ino
- examples/ConnectNoEncryption/ConnectNoEncryption.ino
- examples/ConnectWithWEP/ConnectWithWEP.ino
- examples/ConnectWithWPA/ConnectWithWPA.ino
- examples/ScanNetworks/ScanNetworks.ino
- examples/ScanNetworksAdvanced/ScanNetworksAdvanced.ino
- examples/WiFiChatServer/WiFiChatServer.ino
- examples/WiFiPing/WiFiPing.ino
- examples/WiFiSSLClient/WiFiSSLClient.ino
- examples/WiFiUdpNtpClient/WiFiUdpNtpClient.ino
- examples/WiFiUdpSendReceiveString/WiFiUdpSendReceiveString.ino
- examples/WiFiWebClient/WiFiWebClient.ino
- examples/WiFiWebClientRepeating/WiFiWebClientRepeating.ino
- examples/WiFiWebServer/WiFiWebServer.ino
- Modified the MAC address print in the library's examples.
- Modified Examples documentations
Resolve https://github.com/arduino-libraries/WiFiNINA/issues/32.
> Modified MAC address print

- src/utility/spi_drv.cpp
> Do not put the reset pin mode in input mode on end

- src/WiFiClient.cpp
Added socket check status in WiFiClient::connectSSL
cc/ @sandeepmistry 
resolve https://github.com/arduino-libraries/ArduinoHttpClient/issues/44
> Add socket check  availability in WiFiClient::connectSSL

- .travis.yml
- examples/Tools/FirmwareUpdater/ESP32BootROM.cpp
- examples/Tools/FirmwareUpdater/ESP32BootROM.h
- examples/Tools/FirmwareUpdater/FirmwareUpdater.ino
- examples/Tools/SerialNINAPassthrough/SerialNINAPassthrough.ino
The new baud rate change depends on https://github.com/arduino-libraries/WiFi101-FirmwareUpdater-Plugin/pull/28.
> Add firmware updater supporter for Uno WiFi Rev2

- keywords.txt
- src/WiFi.cpp
- src/WiFi.h
- src/utility/wl_definitions.h
Added timeout logic check on  WiFiClass's begin API
@sandeepmistry tested with the following sketch and works:
```C++
#include <SPI.h>
#include <WiFiNINA.h>
#include "arduino_secrets.h"
///////please enter your sensitive data in the Secret tab/arduino_secrets.h
char ssid[] = SECRET_SSID;        // your network SSID (name)
char pass[] = SECRET_PASS;    // your network password (use for WPA, or use as key for WEP)
int keyIndex = 0;            // your network key Index number (needed only for WEP)
int statusm = WL_IDLE_STATUS;
char server[] = "example.org";
void setup() {
Serial1.begin(115200);
Serial.begin(9600);
while (!Serial) {
;
}
WiFi.setTimeout(150);
Serial.println("begin");
pinMode(8, OUTPUT);
if (WiFi.status() == WL_NO_MODULE) {
Serial.println("error");
while (true);
}
String fv = …
```
> Add WiFiClass::setTimeout(...) API's to set timeout of begin

- examples/AP_SimpleWebServer/AP_SimpleWebServer.ino
- examples/ConnectNoEncryption/ConnectNoEncryption.ino
- examples/ConnectWithWEP/ConnectWithWEP.ino
- examples/ConnectWithWPA/ConnectWithWPA.ino
- examples/ScanNetworks/ScanNetworks.ino
- examples/ScanNetworksAdvanced/ScanNetworksAdvanced.ino
- examples/SimpleWebServerWiFi/SimpleWebServerWiFi.ino
- examples/WiFiChatServer/WiFiChatServer.ino
- examples/WiFiPing/WiFiPing.ino
- examples/WiFiSSLClient/WiFiSSLClient.ino
- examples/WiFiUdpNtpClient/WiFiUdpNtpClient.ino
- examples/WiFiUdpSendReceiveString/WiFiUdpSendReceiveString.ino
- examples/WiFiWebClient/WiFiWebClient.ino
- examples/WiFiWebClientRepeating/WiFiWebClientRepeating.ino
- examples/WiFiWebServer/WiFiWebServer.ino
This way the NINA firmware version will only need to be updated in one place in the library.
Fixes https://github.com/arduino-libraries/WiFiNINA/issues/64
> Use WIFI_FIRMWARE_LATEST_VERSION in example sketch FW version checks

- examples/WiFiUdpSendReceiveString/WiFiUdpSendReceiveString.ino
We have to just increase the size of packetBuffer declared to [256] so that on line 83 no error occur
> size of packetBuffer declared to [255]

- src/utility/spi_drv.cpp
Also initialize SPI later since pins are shared
> RP2040: use NINA_GPIOIRQ instead than GPIO0

- examples/WiFiWebClientRepeating/WiFiWebClientRepeating.ino
Updating comment to match code in next line, no changes to code.
> PUT -> GET typo

- src/WiFi.h
See https://github.com/arduino/nina-fw/releases/tag/1.4.4 .
> Upgrade constant containing latest nina-fw version is 1.4.4.

- src/WiFi.h
https://github.com/arduino/nina-fw/releases/tag/1.4.5
> Update nina-fw version string of latest available nina-fw to 1.4.5

- src/WiFi.h
https://github.com/arduino/nina-fw/releases/tag/1.4.6
> Update constant WIFI_FIRMWARE_LATEST_VERSION to 1.4.6

- docs/api.md
- Updated titles
- Fixed typos
> Documentation update

- README.adoc
- docs/api.md
Several sections in `docs/api.md` had formatting errors due to missing bulletpoints.
> Update MD formatting 

- docs/api.md
We are moving asciilogo.txt to a different domain arduino.tips so we need to change the example
> Moving asciilogo to a different domain

- docs/api.md
- src/WiFiServer.cpp
- src/WiFiServer.h
For other WiFi libraries it is a problem to implement proper server.status(), but easy to implement operator bool.
Server implementation in the Ethernet library has operator bool. WiFi101 has status(), but it just returns 0.
WiFiServer in esp32 Arduino WiFi library has only bool operator too.
So I thought WiFiNINA should have WiFiServer bool operator too.
overview of Server implementations in libraries https://github.com/JAndrassy/Arduino-Networking-API/blob/main/ArduinoNetAPILibs.md#server-class
> WiFiServer operator bool

- src/WiFiClient.cpp
- src/WiFiClient.h
- src/WiFiSSLClient.cpp
- src/WiFiSSLClient.h
- src/utility/server_drv.cpp
- src/utility/server_drv.h
- src/utility/wifi_spi.h
Needs https://github.com/arduino/nina-fw/pull/106
> Add command to override BearSSL TrustAnchor
