src/utility/wifi_drv.cpp

Related to #18.
Two changes:
1) If the result of `REQ_HOST_BY_NAME_CMD` comes through the data value contains the result of the DNS lookup (1 for success, and 0 for failure), use this in the return code.
2) Removed the unnecessary retry for the `GET_HOST_BY_NAME_CMD` command. If it returns 0xffffffff, then the DNS lookup failed. No need to retry.

Speed up resolving bad host names

---

examples/WiFiWebClientRepeating/WiFiWebClientRepeating.ino

Changed the server url in WiFiWebClientRepeating.ino example, due to the dismission of http://arduino.cc
cc/ @sandeepmistry 
porting of https://github.com/arduino-libraries/WiFi101/pull/254

Changed arduino.cc in example.org

---

src/utility/wifi_drv.h
src/utility/wl_definitions.h

As suggested by @ilcato.
When used in conjunction with https://github.com/arduino/nina-fw/pull/9, I can connect to my AP in ~4.2 to ~4.7 seconds.

Increase poll time of checking connection status to 100ms on begin, also adjust retry count accordingly

---

src/WiFiServer.cpp
src/WiFiServer.h

WiFiServer: check previous received client socket for data before querying a new one

---

.travis.yml
examples/ConnectWithWPA2Enterprise/ConnectWithWPA2Enterprise.ino
examples/ConnectWithWPA2Enterprise/arduino_secrets.h
keywords.txt
src/WiFi.cpp
src/WiFi.h
src/utility/wifi_drv.cpp
src/utility/wifi_drv.h
src/utility/wifi_spi.h

This PR replaces #75 and would resolve https://github.com/arduino-libraries/WiFiNINA/issues/26.
It depends on the following firmware changes: https://github.com/arduino/nina-fw/pull/43
I've only tested with an OpenWRT + FreeRADIUS based AP.

WPA2 Enterprise support: PEAP/MSCHAPv2

---

CHANGELOG
library.properties

Depends on https://github.com/arduino/Arduino/pull/9552 for new WPA2 Enterprise features.

Version 1.5.0

---

examples/WiFiStorage/WiFiStorage.ino
src/WiFi.h
src/WiFiStorage.cpp
src/WiFiStorage.h
src/utility/spi_drv.cpp
src/utility/spi_drv.h
src/utility/wifi_drv.cpp
src/utility/wifi_drv.h
src/utility/wifi_spi.h

SIbling PR: https://github.com/arduino/nina-fw/pull/32

Add helpers for Filesystem operations

---

src/utility/server_drv.cpp

This should help a little with https://github.com/arduino-libraries/WiFiNINA/issues/80.

Use SpiDrv::available() to speed up ServerDrv::getDataBuf(...) in no socket data scenario

---

src/WiFiStorage.h
src/utility/wifi_drv.cpp
src/utility/wifi_drv.h
src/utility/wifi_spi.h

Test sketch ...
```C++
#include <WiFiNINA.h>
void setup() {
Serial.begin(115200);
while (!Serial) { }
int status = WL_IDLE_STATUS;
do {
status = WiFi.begin("SSID", "PASS");
delay(5000);
} while ( status != WL_CONNECTED);
/* Download new files. */
if (!WiFiStorage.downloadOTA("https://downloads.arduino.cc/test/wifi1010-sha256-remote.ota")) {
Serial.println("WiFiStorage.downloadOTA(...) error");
return;
}
Serial.println("Download complete");
/* Read length. */
len = 0;
if (WiFiStorage.exists("/fs/UPDATE.BIN.LZSS", &len)) {
Serial.print("File size = ");
Serial.println(len);
} else {
Serial.println("WiFiStorage.open(...) error");
}
}
void loop()
{
}
```
Related PRs:
* https://github.com/arduino/nina-fw/pull/53
* https://github.com/arduino/ArduinoCore-samd/pull/553

Add 'downloadOTA' command to download OTA file and verify length/CRC

---

src/WiFiStorage.h

Reason: The receive buffer on the nina firmware can't hold more than [128 bytes](https://github.com/arduino/nina-fw/blob/master/main/CommandHandler.cpp#L1404).
CC @eclipse1985 @luigigubello

Limit the maximum length of the download URL for the OTA binary to 128 bytes

---

src/WiFi.h

Bugfix: The latest available wifi firmware version is in fact 1.4.1, not 1.4.2

---

src/WiFiClient.cpp
src/WiFiClient.h

This PR, together with [nina-fw PR #62](https://github.com/arduino/nina-fw/pull/62), would solve issue [#61](https://github.com/arduino/nina-fw/issues/61) of nina-fw. 
In the previous implementation, as soon as a write failed, the socket was closed and the connection dropped. Failures happen especially when large files are sent (100k-1M characters). 
The provided modifications avoid to immediately drop the connection. The same packet can be sent up to 5 times. Only after 5 consecutive failures the socket will be closed.
The retry will be enabled by default. However, if the user doesn't want to enable it and close the communication at the first failure (previous behavior), he/she can disable it with `setRetry(false)`.
The new function `retry(const uint8_t *buf, size_t size, bool write)` is …

Add possibility to resend data if lwip_send fails

---

src/utility/server_drv.cpp
src/utility/spi_drv.cpp
src/utility/spi_drv.h

Within the Arduino IoT Cloud firmware stack we are using a watchdog to prevent unintended application lockup. Unfortunately in certain situations the connection attempt undertaken within WiFiNINA can take so long that the watchdog is triggered although everything is fine. This change is feeding the watchdog (if one is present) so to avoid prematurely triggering of the watchdog.

Bugfix: Feed watchdog within busy-wait-loop within connectBearSSL to prevent a premature reset.

---

src/utility/spi_drv.cpp

Instead of using the cumbersome __has_include approach rather define a weak function to be overwritten by higher level application layers.

Replace __has_include for watchdog with weak function.

---

examples/Tools/FirmwareUpdater/ESP32BootROM.cpp

FW can be flashed using the modified sketch, `FirmwareUpdater` utility from https://github.com/arduino/FirmwareUpdater/releases/tag/0.1.2 and this commandline
```
./FirmwareUploader -model nina -firmware /path/to/NINA_W102.bin -port /dev/ttyPortName
```
NINA FW attached
[NINA_W102.bin.zip](https://github.com/arduino-libraries/WiFiNINA/files/6190529/NINA_W102.bin.zip)

Add support to RP2040 on FirmwareUpdater

---

src/WiFiClient.cpp

- 'no return of non-void-function'

[BUGfix]: prevent Compiler warning in WiFiClient.cpp!

---

.github/dependabot.yml
.github/workflows/check-arduino.yml
.github/workflows/compile-examples.yml
.github/workflows/report-size-deltas.yml
README.adoc

This PR updates the CI system to the standardized [GitHub Actions](https://github.com/features/actions)-based CI configuration for Arduino libraries.
Dependabot will periodically check the versions of all actions used in the repository's workflows. If any are found to be outdated, it will submit a pull request to update them.
NOTE: Dependabot's PRs will sometimes try to pin to the patch version of the action (e.g., updating `uses: foo/bar@v1` to `uses: foo/bar@v2.3.4`). When the action author has [provided a major version ref](https://docs.github.com/en/actions/creating-actions/about-actions#using-release-management-for-actions), use that instead (e.g., `uses: foo/bar@v2`). Once the major version has been updated in the workflow, Dependabot should not submit an update PR again until the …

Update continuous integration system

---

src/utility/nano_rp2040_support.cpp
src/utility/wifi_drv.cpp
src/utility/wifi_drv.h
src/utility/wifi_spi.h

For Arduino `Nano RP2040 Connect` which has those pins as well as the RGB LED directly connected to the NINA-W102.
Related: https://github.com/arduino/nina-fw/pull/64

Allow access to RGB LED as well as A4-A7 via classic Arduino APIs

---

src/WiFi.cpp
src/WiFi.h
src/utility/spi_drv.cpp

Instead of relying on the 'hidden mechanism' of passing a function to feed the watchdog via a weak function definition pass a function pointer via a public API instead. This increases visibility and reduces unintentional introductions of bugs.

Provide clean API for passing watchdog function

---

src/WiFi.h

Due to the release of nina-fw:v1.4.7 (https://github.com/arduino/nina-fw/releases/tag/1.4.7) this version number needs to be incremented.

Increment WIFI_FIRMWARE_LATEST_VERSION to 1.4.7

---

examples/SimpleWebServerWiFi/SimpleWebServerWiFi.ino

This example contains a hard-coded pin number for the built-in LED, but this is not portable across all boards. This pull request replaces it with the safer `LED_BUILTIN` constant.

Replace hard-coded LED pin number with the portable LED_BUILTIN constant

---

examples/WiFiUdpNtpClient/WiFiUdpNtpClient.ino

For some reason the example failed to get a response from the IP address of `time.nist.gov`. I also didn't get a ping reply from that address to my laptop.
I had more luck with one of the servers of `pool.ntp.org`.
For the record I'm located in Amsterdam, Netherlands. Does this new address work in US and other parts of the world?

Fix address of NTP server in example

---

docs/api.md

Replace double turned comma quotes (U+201C, U+201D) with programmer's double quotes (U+0022).
Some of the example code snippets use unicode fancy quotes instead of normal plain double quotes. This throws a compile error if the examples are copy/pasted into sketches.

Replace unicode left/right quotes with normal quotes

---

docs/api.md
examples/WiFiAdvancedChatServer/WiFiAdvancedChatServer.ino
examples/WiFiAdvancedChatServer/arduino_secrets.h
src/WiFiServer.cpp
src/WiFiServer.h
src/utility/server_drv.cpp
src/utility/server_drv.h

---
_The [first PR for server.accept](https://github.com/arduino-libraries/WiFiNINA/pull/204) was destroyed by GitHub Sync function, when I today attempted to sync the old branch for server.accept() with current master to get the current version of api.md. Sorry. This one is based on current `master` branch._
_Note that https://github.com/arduino-libraries/WiFiNINA/pull/204 already received approval from multiple project maintainers._
---
`server.accept()` depends on nina-fw PR https://github.com/arduino/nina-fw/pull/79 (merged)
This PR adds `server.accept()` function as documented for the Ethernet library:
https://www.arduino.cc/en/Reference/EthernetServerAccept
If `server.accept()` is used with older firmware it will behave as `available()`, because the accept parameter in SPI request …

added server.accept()

---

src/WiFiClient.cpp
src/WiFiClient.h
src/WiFiSSLClient.cpp
src/WiFiSSLClient.h
src/utility/server_drv.cpp
src/utility/server_drv.h
src/utility/wifi_spi.h

Needs https://github.com/arduino/nina-fw/pull/107

Add command to read BearSSL client errorCode

---

docs/api.md
src/WiFiClient.cpp
src/WiFiClient.h
src/utility/server_drv.cpp
src/utility/server_drv.h

Following the support in the firmware in https://github.com/arduino/nina-fw/pull/89, here is the implementation of WiFiClient.connect timeout.
Additionally the strange 10 seconds waiting time is removed.
overview of Client API in Arduino networking libraries:
https://github.com/JAndrassy/Arduino-Networking-API/blob/main/ArduinoNetAPILibs.md#client-getters-and-setters

WiFiClient connect timeout

---

src/WiFi.cpp

code copied from the Ethernet library `begin` functions

WiFi.config - setting defaults as the Ethernet library

---

examples/WiFiWebClientBLELed/WiFiWebClientBLELed.ino
examples/WiFiWebClientBLELed/arduino_secrets.h
src/utility/wifi_drv.cpp
src/utility/wifi_drv.h
src/utility/wifi_spi.h

This feature depends on the following PR https://github.com/arduino/nina-fw/pull/99, introducing breaking changes in ArduinoBLE library

 Changing BLE hci transport
